config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe/webhook' # provide a custom path

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", registrations: "registrations" }

  resource :subscription
  resource :card
  
  resources :participants
  resources :results

  get '/.well-known/acme-challenge/:id' => 'visitors#letsencrypt'

  get '/participants/new', to: 'participants#create'
  resources :jsons, except: [:new, :edit, :index]
  get 'jsons', to: 'jsons#index'
  get '/jsons/u/:dashboardid', to: 'jsons#index'
  get "content/silver"
  get "content/gold"
  get "content/platinum"
  root to: 'visitors#index'
  get 'products/:id', to: 'products#show', :as => :products

  resources :users
  resources :dashboards
  get 'surveyresults/:id', to: 'dashboards#surveyresults'
  get 'survey/:id', to: 'surveys#survey'
  get '/finished', to: 'visitors#finished'

  get 'dashboards/:id/tree', to: 'dashboards#tree'
  get 'dashboards/:id/tasks', to: 'dashboards#tasks'
  get 'dashboards/:id/surveyinfo', to: 'dashboards#surveyinfo'
  get 'surveyresults/:id/overview', to: 'dashboards#overview'
  get 'surveyresults/:id/taskanalysis', to: 'dashboards#taskanalysis'
  get 'surveyresults/:id/participants', to: 'dashboards#participants'
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  before_action :redirect_to_signup, only: [:new]

  def show
  end

  def new
  end

  def create
    customer = if current_user.stripe_id?
                 Stripe::Customer.retrieve(current_user.stripe_id)
               else
                 Stripe::Customer.create(email: current_user.email)
               end

    subscription = customer.subscriptions.create(
      source: params[:stripeToken],
      plan: params[:planid]
    )

    options = {
      stripe_id: customer.id,
      stripe_subscription_id: subscription.id,
    }

    # Only update the card on file if we're adding a new one
    options.merge!(
      card_last4: params[:card_last4],
      card_exp_month: params[:card_exp_month],
      card_exp_year: params[:card_exp_year],
      card_type: params[:card_brand]
    ) if params[:card_last4]

    current_user.update(options)

    redirect_to root_path
  end

  def destroy
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete
    current_user.update(stripe_subscription_id: nil)

    redirect_to root_path, notice: "Your subscription has been canceled."
  end

  def plans
    @stripe_list = Stripe::Plan.all
    @plans = @stripe_list[:data]
  end

  private

    def redirect_to_signup
      if !user_signed_in?
        session["user_return_to"] = new_subscription_path
        redirect_to new_user_registration_path
      end
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/new.html.erb
        <!-- ========== HEADER ========== -->
        <header class="header main-header header-style-3" id="circular-particles">
            <div class="primary-trans-bg">
                <div class="container">
                    <!-- For centering the content vertically -->
                    <div class="outer">
                        <div class="inner">
                            <div class="row">
                                <div class="col-md-6 col-sm-8 col-md-offset-3 col-sm-offset-2 form-wrap">
                                    <div class="text-center logo-wrap">
                                        <a href="/"><img src="/frontend/images/dark-logo.png" alt="" width="125"></a>
                                    </div> <!-- end text-center -->

                                      <%= form_tag subscription_path, id: "payment-form" do %>
                                      <% if current_user.card_last4? %>
                                        <div class="card-on-file">
                                          <p>Your current card on file is:</p>
                                          <div><%= current_user.card_type %> **** **** **** <%= current_user.card_last4 %></div>
                                          <div>Expires <%= current_user.card_exp_month %> / <%= current_user.card_exp_year %></div>

                                          <p><%= link_to "Use a different card", "#", class: "use-different-card" %></p>
                                        </div>
                                      <% end %>

                                      <div class="card-fields <%= card_fields_class %>">
                                        <span class="payment-errors"></span>

                                        <div class="form-row">
                                          <label>
                                            <span>Card Number</span>
                                            <input value="" class="form-control" type="text" size="20" data-stripe="number"/>
                                          </label>
                                        </div>

                                        <div class="form-row">
                                          <label>
                                            <span>CVC</span>
                                            <input value="" class="form-control" type="text" size="4" data-stripe="cvc"/>
                                          </label>
                                        </div>

                                        <div class="form-row">
                                          <span style="font-weight: bold;">Expiration (MM/YYYY)</span>
                                          <label>
                                            <input value="" type="text" size="2" data-stripe="exp-month" style="width:45%; float:left;" />
                                            <span style="width:9%; text-align: center; float:left; margin-top:10px;"> / </span>
                                            <input value="" type="text" size="4" data-stripe="exp-year" style="width:45%; float:left;" />
                                          </label>
                                        </div>
                                      </div>
                                      <input type="hidden" name="planid" value="monthly">

                                      <button type="submit" style="padding-top:0px;" class="btn se-btn btn-rounded">Submit Payment</button>
                                    <% end %>

                                </div>
                            </div> <!-- end row -->
                        </div> <!-- end inner -->
                    </div> <!-- end outer -->
                </div> <!-- end container -->
            </div> <!-- end primary-trans-bg -->
        </header>