config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe/webhook' # provide a custom path

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", registrations: "registrations" }

  resource :subscription
  resource :card
  
  resources :participants
  resources :results

  get '/.well-known/acme-challenge/:id' => 'visitors#letsencrypt'

  get '/participants/new', to: 'participants#create'
  resources :jsons, except: [:new, :edit, :index]
  get 'jsons', to: 'jsons#index'
  get '/jsons/u/:dashboardid', to: 'jsons#index'
  get "content/silver"
  get "content/gold"
  get "content/platinum"
  root to: 'visitors#index'
  get 'products/:id', to: 'products#show', :as => :products

  resources :users
  resources :dashboards
  get 'surveyresults/:id', to: 'dashboards#surveyresults'
  get 'survey/:id', to: 'surveys#survey'
  get '/finished', to: 'visitors#finished'

  get 'dashboards/:id/tree', to: 'dashboards#tree'
  get 'dashboards/:id/tasks', to: 'dashboards#tasks'
  get 'dashboards/:id/surveyinfo', to: 'dashboards#surveyinfo'
  get 'surveyresults/:id/overview', to: 'dashboards#overview'
  get 'surveyresults/:id/taskanalysis', to: 'dashboards#taskanalysis'
  get 'surveyresults/:id/participants', to: 'dashboards#participants'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.admin?

        can :manage, :all

    else

        can :update, Dashboard do |dashboard|
            dashboard.user == user
        end
        can :create, Dashboard do |dashboard|
            dashboard.user == user
        end
        can :show, Dashboard do |dashboard|
            dashboard.user == user
        end
        can :destroy, Dashboard do |dashboard|
            dashboard.user == user
        end


        can :update, Cardtool do |cardtool|
            cardtool.user == user
        end
        can :create, Cardtool do |cardtool|
            cardtool.user == user
        end
        can :show, Cardtool do |cardtool|
            cardtool.user == user
        end
        can :destroy, Cardtool do |cardtool|
            cardtool.user == user
        end


    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/cardtool.rb
class Cardtool < ActiveRecord::Base
	belongs_to :user
end

app/models/charge.rb
class Charge < ActiveRecord::Base
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
	belongs_to :user

	has_many :questions
	accepts_nested_attributes_for :questions, allow_destroy: true
end

app/models/json.rb
class Json < ActiveRecord::Base

end

app/models/participant.rb
class Participant < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :dashboard
  has_many :answers
  accepts_nested_attributes_for :answers, allow_destroy: true
end

app/models/result.rb
class Result < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :admin, :yearly, :monthly]
  after_initialize :set_default_role, :if => :new_record?
  # after_create :sign_up_for_mailing_list


  has_many :dashboards
  has_many :cardtools

  def set_default_role
    self.role ||= :user
  end


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
     :omniauthable, :omniauth_providers => [:facebook, :twitter]

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end

  def subscribed?
    stripe_subscription_id?
  end


end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	before_action :authenticate_user!

	def update
	    customer = Stripe::Customer.retrieve(current_user.stripe_id)
	    subscription = customer.subscriptions.retrieve(current_user.stripe_subscription_id)
	    subscription.source = params[:stripeToken]
	    subscription.save

	    current_user.update(
	      card_last4: params[:card_last4],
	      card_exp_month: params[:card_exp_month],
	      card_exp_year: params[:card_exp_year],
	      card_type: params[:card_brand]
	    )

	    redirect_to edit_user_registration_path, notice: "Successfully updated your card"
	end
end

app/controllers/jsons_controller.rb
class JsonsController < ApplicationController
  before_action :set_json, only: [:show, :update, :destroy]
  # GET /jsons
  # GET /jsons.json
  def index
    @jsons = Json.where(dashboardid: params[:dashboardid])
    render json: @jsons
  end

  # GET /jsons/1
  # GET /jsons/1.json
  def show
    render json: @json
  end

  # POST /jsons
  # POST /jsons.json
  def create
    @json = Json.new(json_params)

    if @json.save
      render json: @json, status: :created, location: @json
    else
      render json: @json.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /jsons/1
  # PATCH/PUT /jsons/1.json
  def update
    @json = Json.find(params[:id])

    if @json.update(json_params)
      head :no_content
    else
      render json: @json.errors, status: :unprocessable_entity
    end
  end

  # DELETE /jsons/1
  # DELETE /jsons/1.json
  def destroy
    @json.destroy

    head :no_content
  end

  private

    def set_json
      @json = Json.find(params[:id])
    end

    def json_params
      params.require(:json).permit(:text, :parent, :id, :dashboardid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields btn btn-default", data: {id: id, fields: fields.gsub("\n", "")})
  end

  def card_fields_class
    "hidden" if current_user.card_last4?
  end

end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cardtool_helper.rb
module CardtoolHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64585191-2', 'auto');
  ga('send', 'pageview');

</script>

<script type="text/javascript">
var _mfq = _mfq || [];
  (function() {
    var mf = document.createElement("script");
    mf.type = "text/javascript"; mf.async = true;
    mf.src = "//cdn.mouseflow.com/projects/f6c67e4f-f1ba-4d17-99b0-fe7c13e3215a.js";
    document.getElementsByTagName("head")[0].appendChild(mf);
  })();
</script>

<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>

<!--  Displays logged in, logged out, etc. 


<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>



-->

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'TreeTool', dashboards_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
	<li>
		<%= link_to 'Pricing', page_path('pricing') %>
	</li>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign Up', new_user_registration_path(:plan => 'free'), data: { no_turbolink: true } %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
  
<header class="navbar navbar-inverse normal" role="banner">
  <div class="container">
    <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="<%= root_path %>" class="navbar-brand">Optimal Suite</a>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        <ul class="nav navbar-nav navbar-right">
          <%= render 'layouts/navigation_links' %>
          <%= render 'layouts/nav_links_for_auth' %>
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About Us', page_path('about') %></li>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <!-- ========== VIEWPORT META ========== -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

        <!-- ========== PAGE TITLE ========== -->
        <title><%= content_for?(:title) ? yield(:title) : "User Experience Testing" %></title>

        <!-- ========== META TAGS ========== -->
        <meta name="description" content="User Experience Testing Tools for Information Architecture.">
        <meta name="keywords" content="tree testing, ux testing, user research">

        <!-- ========== FAVICON & APPLE ICONS ========== -->
        <%= favicon_link_tag 'favicon.ico' %>
        <link rel="apple-touch-icon" href="/frontend/images/apple-touch-icon.png">

        <!-- ========== MINIFIED VENDOR CSS ========== -->
        <link rel="stylesheet" href="/frontend/styles/vendor.css">
        <link rel="stylesheet" href="/frontend/styles/main.css">

        <!-- ========== MODERNIZR ========== -->
        <script src="/frontend/scripts/vendor/modernizr.js"></script>
        <%= tag :meta, name: "stripe-key", content: Rails.application.secrets.stripe_publishable_key %>
        <script type="text/javascript" src="https://js.stripe.com/v2/"></script>

        <%= javascript_include_tag 'application' %>

        <%= render 'layouts/google_analytics' %>

        <%= csrf_meta_tags %>
        <%= yield(:head) %>

    </head>

    <!-- ========== BODY ==========
    .light-header: for light colored header
    .dark-header: for dark colored header
    ==========  ========== -->
    <body class="dark-header animsition">

        <!-- ========== NAVIGATION ========== -->
      <nav class="navbar yamm navbar-fixed-top" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button> <!-- end navbar-toggle -->
            <a class="navbar-brand" href="/">
              <img src="/frontend/images/light-logo.png" alt="Logo" class="light-logo">
              <img src="/frontend/images/dark-logo.png" alt="Logo" class="dark-logo">
            </a> <!-- end navbar-brand -->
          </div> <!-- end navbar-header -->

          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">

                <% if user_signed_in? %>
              <li>
                  <%= link_to 'About Us', page_path('about') %>
                </li>
              <li><%= link_to 'TreeTool', dashboards_path %></li>
              <li><%= link_to 'Edit account', edit_user_registration_path %></li>
              
                <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
            <% else %>
                <li class="active dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
                              <ul class="dropdown-menu animated fadeIn">
                    <li>
                                      <div class="yamm-content">
                                          <div class="nav-col">
                                              <ul>
                                                  <li><a href="/pages/treetool">TreeTool</a></li>
                                              </ul>
                                          </div> <!-- end nav-col -->
                                      </div> <!-- end yamm-content -->
                    </li>
                  </ul> <!-- end dropdown-menu -->
                </li>
                <li>
                    <%= link_to 'About Us', page_path('about') %>
                  </li>
                <li>
                    <%= link_to 'Pricing', page_path('pricing') %>
                  </li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li class="nav-btn-wrap">
                            <span class="nav-btn"><a href="<%= new_user_registration_path %>" class="btn se-btn-black btn-rounded">Sign Up</a></span>
                        </li>
              <!-- <li><%= link_to 'Sign up', new_user_registration_path, data: { no_turbolink: true } %></li> -->
            <% end %>

            </ul> <!-- end navbar-nav -->

          </div> <!--end nav-collapse -->
        </div> <!-- end container -->
      </nav>

        <%= yield %>

        <!-- ========== FOOTER ========== -->
        <footer class="light-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-2 col-sm-3 col-xs-6">
                        <img src="/frontend/images/dark-logo.png" alt="" class="footer-logo">
                    </div>

                    <div class="col-md-2 col-sm-3 col-xs-6">
                        <h6 class="mtn">General</h6>
                        <ul>
                            <li><a href="<%= new_user_registration_path %>">Sign Up</a></li>
                            <li><a href="<%= new_user_session_path %>">Login</a></li>
                            <li><a href="/pages/privacypolicy">Privacy Policy</a></li>
                            <li><a href="/pages/termsconditions">Terms of Service</a></li>
                        </ul>
                    </div>

                    <div class="col-md-2 col-sm-3 col-xs-6">
                        <h6 class="mtn">PAGES</h6>
                        <ul>
                            <li><a href="/pages/about">About Us</a></li>
                            <li><a href="/pages/pricing">Pricing</a></li>
                            <li><a href="/pages/treetool">TreeTool</a></li>
                        </ul>
                    </div>


                    
                    <div class="col-md-4 col-sm-8 col-sm-offset-2 col-md-offset-0">
                        <h6 class="mtn">SUBSCRIBE</h6>
                        <div class="input-group">
                            <input type="email" class="form-control inp-rounded" placeholder="Enter your email id">
                            <span class="input-group-btn">
                                <button class="btn se-btn btn-rounded" type="button">Subscribe!</button>
                            </span> <!-- end input-group-btn -->
                        </div><!-- end input-group -->
                        <p class="text-center text-muted">We don't spam!</p>
                    </div>
                    

                </div> <!-- end row -->

                <div class="row footer-bottom">
                    <div class="col-md-6">
                        <p>Copyright &copy; Optimal Suite. 2016. All Rights Reserved.</p>
                    </div>

                    <div class="col-md-6 text-right">
                        <h6><a href="#">FACEBOOK</a></h6>
                        <h6><a href="#">TWITTER</a></h6>
                        <h6><a href="#">LINKEDIN</a></h6>
                        <h6><a href="#">GOOGLE PLUS</a></h6>
                    </div>
                </div> <!-- end footer-bottom -->
            </div> <!-- end container -->
        </footer>


      <script src="/frontend/scripts/vendor.js"></script>

        <!-- ========== MINIFIED PLUGINS JS ========== -->
      <script src="/frontend/scripts/plugins.js"></script>

      <script src="/frontend/scripts/main.js"></script>
    </body>

</html>

app/views/layouts/backend_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Optimal Suite" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Optimal Suite Tools" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag 'application' %>

    <%= tag :meta, name: "stripe-key", content: ENV['stripe-publishable-key'] %>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>

    <style>
      html {
        min-height:100%;
        margin: 0;
      }
    </style>

    <%= favicon_link_tag 'favicon.ico' %>
    <%= render 'layouts/google_analytics' %>

    <%= csrf_meta_tags %>

  
        <!-- Theme CSS -->
    <link href="/assets/css/DashCustom.min.css" rel="stylesheet">
    <script href="/assets/javascript/DashCustom.js"></script>
    <script href="/assets/javascript/DashCustom.min.js"></script>

        <!-- Bootstrap -->
    <link href="/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/vendors/nprogress/nprogress.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/build/css/custom.min.css" rel="stylesheet">


    <%= yield(:head) %>
  </head>


  <body class="nav-md" style="min-height: 100%;">
    <div class="container body" style="min-height: 100%;">
      <div class="main_container" style="min-height: 100%;">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="/dashboards/" class="site_title"><i class="fa fa-tree"></i> <span>TreeTool</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info 
            <div class="profile">
              <div class="profile_pic">
                <img src="images/img.jpg" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>John Doe</h2>
              </div>
            </div>
             /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a href="/dashboards/<%= @dashboard.id %>"><i class="fa fa-edit"></i> Edit Your Campaign </span></a>
                  </li>
                  <li><a href="/dashboards/<%= @dashboard.id %>/tree"><i class="fa fa-desktop"></i> Tree </a>
                  </li>
                  <li><a href="/dashboards/<%= @dashboard.id %>/tasks"><i class="fa fa-table"></i> Tasks </a>
                  </li>
                  <li><a href="/dashboards/<%= @dashboard.id %>/surveyinfo"><i class="fa fa-clone"></i> Survey Information </a>
                  </li>
                    <% if @results.length > 0 %>
                  <li><a><i class="fa fa-bar-chart-o"></i> Results <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/surveyresults/<%= @dashboard.id %>/overview/">Overview</a></li>
                      <li><a href="/surveyresults/<%= @dashboard.id %>/taskanalysis">Task-by-Task</a></li>
                      <li><a href="/surveyresults/<%= @dashboard.id %>/participants">Participants</a></li>
                    </ul>
                  </li>
                    <% end %>
                  <li><a href="/dashboards/"><i class="fa fa-home"></i> See All Campaigns </a>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
             /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu" style="margin-bottom:-15px;">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars" style="margin-bottom:15px;"></i></a>
              </div>

              
              <ul class="nav navbar-nav navbar-right">
              <!-- 
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    Account Settings
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li>
                      <a href="<%= edit_user_registration_path %>">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Settings</span>
                      </a>
                    </li>
                    <li><a href="javascript:;">Help</a></li>
                    <li><a href="<%= destroy_user_session_path %>"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>



                <li role="presentation" class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="text-center">
                        <a>
                          <strong>See All Alerts</strong>
                          <i class="fa fa-angle-right"></i>
                        </a>
                      </div>
                    </li>
                  </ul>
                </li>

                -->

              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        
          <div class="right_col" role="main" style="min-height:100%; clear:both;">
            <%= yield %>
          </div>
        <!-- /page content -->

        <!-- footer content 
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        /footer content -->
      </div>
    </div>


    <!-- Bootstrap -->
    <script src="/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/vendors/nprogress/nprogress.js"></script>
    
    <!-- Custom Theme Scripts -->
    <script src="/build/js/custom.min.js"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!doctype html>
<html class="no-js" lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

      <title><%= content_for?(:title) ? yield(:title) : "Optimal Suite" %></title>

        <!-- ========== META TAGS ========== -->
        <meta name="description" content="User Experience Testing Tools for Information Architecture.">

        <!-- ========== FAVICON & APPLE ICONS ========== -->
        <%= favicon_link_tag 'favicon.ico' %>

        <!-- ========== MINIFIED VENDOR CSS ========== -->
        <link rel="stylesheet" href="/frontend/styles/vendor.css">
        <link rel="stylesheet" href="/frontend/styles/main.css">

        <!-- ========== MODERNIZR ========== -->
      <script src="/frontend/scripts/vendor/modernizr.js"></script>


      <%= favicon_link_tag 'favicon.ico' %>
      <%= render 'layouts/google_analytics' %>


      <%= javascript_include_tag 'application' %>
      <%= csrf_meta_tags %>
      <%= yield(:head) %>

    </head>

     <%= yield %>

      <script src="/frontend/scripts/vendor.js"></script>

        <!-- ========== MINIFIED PLUGINS JS ========== -->
      <script src="/frontend/scripts/plugins.js"></script>

      <script src="/frontend/scripts/main.js"></script>
    </body>

</html>

app/views/layouts/frontend_layout.html.erb
<!DOCTYPE html>
<html id="please">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Optimal Suite" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Optimal Suite Tools" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>

        <!-- stylesheets -->
    <link rel="stylesheet" type="text/css" href="/reacttheme/compiled/theme.css">
    <link rel="stylesheet" type="text/css" href="/reacttheme/vendor/animate.css">
    <style>
      html {
        height:100% !important;
        margin: 0;
      }
    </style>

    <%= favicon_link_tag 'favicon.ico' %>
    <%= render 'layouts/google_analytics' %>


    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>

    
     <%= render 'layouts/navigation' %>
     <%= yield %>


</html>